#!/bin/bash
# Usage: ./run_AMTSP problem_name salesmen objective max_trials runs [[min_size max_size] [optimum ]]

if [ -z "$5" ]; then
    echo "Usage: ./run_AMTSP problem_name salesmen objective max_trials runs [[min_size max_size] [optimum]]"
    exit
fi

lkh="../LKH"
name=$1
salesmen=$2
mtsp_objective=$3
max_trials=$4
runs=$5
par=TMP/$name.pid$$.par

mkdir -p TOURS
mkdir -p TOURS/ATSP
mkdir -p TOURS/ATSP/$mtsp_objective
mkdir -p TMP

echo "SPECIAL" > $par
echo "PROBLEM_FILE = INSTANCES/ATSP/$name.atsp" >> $par
echo "SALESMEN = $salesmen" >> $par
echo "MTSP_OBJECTIVE = $mtsp_objective" >> $par
echo "MAX_TRIALS = $max_trials" >> $par
echo "RUNS = $runs" >> $par
# echo "TOUR_FILE = TOURS/ATSP/$mtsp_objective/$name.$salesmen.$.tour" >> $par
echo "TRACE_LEVEL = 0" >> $par

if [ -n "$6" ] && [ -z "$7" ]; then
    echo "OPTIMUM = $6" >> $par
fi

if [ -n "$7" ]; then
    echo "MTSP_MIN_SIZE = $6" >> $par
    echo "MTSP_MAX_SIZE = $7" >> $par
fi

if [ -n "$8" ]; then
    echo "OPTIMUM = $8" >> $par
fi

$lkh $par

/bin/rm -f $par
